// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Refraction
{
    internal sealed partial class Vsix
    {
        public const string Id = "Refraction.26e69bc4-ab86-469a-ac8e-f9f16e77ff7e";
        public const string Name = "Refraction";
        public const string Description = "";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "";
        public const string Tags = "";
    }
}
