// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Refraction
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string RefractionGuidString = "3ae3415b-d5b6-4f59-857a-ea156e70ac71";
        public static Guid Refraction = new Guid(RefractionGuidString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int RefractionSettings = 0x0010;
        public const int RefractionSettingsToosButtonGroup = 0x0004;
        public const int DetectBugs = 0x0005;
        public const int AddDebugStatements = 0x0006;
        public const int CreateDocumentation = 0x0007;
        public const int SeparateHardcodedLiterals = 0x0008;
        public const int RefactorCode = 0x0009;
        public const int StyleCheck = 0x0011;
        public const int GenerateUnitTests = 0x0012;
        public const int AddTypes = 0x0013;
        public const int RefractionMenuGroup = 0x0014;
        public const int RefractionMenu = 0x0015;

    }
}