name: Build and Publish VSIX

on:
  push:
    branches:
      - main

env:
  Configuration: Release

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download VSIX PowerShell script
      shell: pwsh
      run: |
        Invoke-WebRequest -Uri https://raw.github.com/madskristensen/ExtensionScripts/master/AppVeyor/vsix.ps1 -OutFile vsix.ps1

    - name: Install VSIX dependencies
      shell: pwsh
      run: |
        powershell -ExecutionPolicy RemoteSigned -File vsix.ps1

    - name: Increment and Update VSIX Version
      run: |
        Vsix-IncrementVsixVersion | Vsix-UpdateBuildVersion
        Vsix-TokenReplacement src\source.extension.cs "Version = `"([0-9\\\.]+)`"" "Version = `"{version}`""

    - name: Restore NuGet packages
      run: nuget restore

    - name: Build VSIX
      run: msbuild /p:configuration=${{ env.Configuration }} /p:DeployExtension=false /p:ZipPackageCompressionLevel=normal /v:m

    - name: Publish VSIX to Gallery
      shell: pwsh
      run: Vsix-PushArtifacts | Vsix-PublishToGallery
      
