name: Build and Publish VSIX

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  Configuration: Release

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download VSIX PowerShell script
      run: |
        Invoke-WebRequest -Uri https://raw.github.com/madskristensen/ExtensionScripts/master/AppVeyor/vsix.ps1 -OutFile vsix.ps1

    - name: Install VSIX dependencies
      run: |
        powershell -ExecutionPolicy RemoteSigned -File vsix.ps1

    - name: Increment and Update VSIX Version
      run: |
        powershell -Command 'Vsix-IncrementVsixVersion | Vsix-UpdateBuildVersion'
        powershell -Command 'Vsix-TokenReplacement src\source.extension.cs "Version = `"([0-9\\\.]+)`"" "Version = `"{version}`""'

    - name: Restore NuGet packages
      run: nuget restore

    - name: Build VSIX
      run: msbuild /p:configuration=${{ env.Configuration }} /p:DeployExtension=false /p:ZipPackageCompressionLevel=normal /v:m

    - name: Publish VSIX to Gallery
      run: powershell -Command 'Vsix-PushArtifacts | Vsix-PublishToGallery'
      
